apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery
        image: celery-worker:latest
        imagePullPolicy: Never
        command: ["celery", "-A", "app.celery_app", "worker", "--loglevel=info"]
        env:
        - name: INFLUXDB_URL
          value: "http://influxdb.monitoring.svc.cluster.local:8086"
        - name: INFLUXDB_TOKEN
          value: "5MkVYJYQHFhUN5p3DqtFsgG31RHvGRgO9Gr2xVVPbkj_53cgtAwJeetOHAiRIIeAkcdvn4205wpjAb8tk_qdog=="
        - name: INFLUXDB_ORG
          value: "fe553ea26a22c3fd"
        - name: INFLUXDB_BUCKET
          value: "sensordata"
        - name: CELERY_BROKER_URL
          value: "amqp://rabbitmq/"
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis-service:6379/0"
        