name: build docker and push to github container registory 

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: set up docker buildx 
        uses: docker/setup-buildx-action@v1

      - name: login to github container registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }} # this could be changed to pat, not added yet

      - name: build and push docker image 
        uses: docker/build-push-action@v2
        with:
          context: . 
          push: true 
          tags: ghcr.io/krishnakantsingh14/deployfastapiapp:testv0